"""Hardware-constrained MatMulV3 candidate search."""

from .domain import (
    KNOWLEDGE_FIELDS,
    BehaviorTarget,
    Candidate,
    GenerationBudget,
    Hardware,
    MeasuredObservation,
    Schedule,
    SearchResult,
    SolverReport,
    Template,
    Workload,
)
from .deployment import (
    DIRECT_BASE_AUDIT_BANK_WORKLOADS,
    DIRECT_BASE_AUDIT_PAIRED_RECORDS,
    DIRECT_BASE_AUDIT_UNIQUE_RECORDS,
    DIRECT_BASE_AUDIT_WINNER_WORKLOADS,
    DIRECT_BASE_AUDIT_WORKLOADS,
    DIRECT_BASE_L2_RESIDENT_RATIO,
    DIRECT_BASE_RULE_VERSION,
    DIRECT_RULE_AUDIT_RECORDS,
    DIRECT_RULE_AUDIT_UNIQUE_RECORDS,
    DIRECT_RULE_AUDIT_WORKLOADS,
    DIRECT_RULE_TEMPLATE_AUDIT,
    direct_base_candidate,
    direct_rule_candidate,
)
from .orchestrator import CandidateEngine, SearchConfig
from .one_shot import (
    AdaptiveCalibrationEvidence,
    BankRelativeEffectModel,
    BankRelativePrediction,
    BankRelativeSafetyModel,
    BankRelativeSafetyPrediction,
    BankRelativeValidation,
    OneShotDecision,
    adaptive_calibration_evidence,
    select_adaptive_calibration_candidates,
    select_calibration_candidates,
    select_one_shot_candidate,
    validate_bank_relative_selector,
)
from .racing import RacingPlan, TemplateEvidence, plan_template_race
from .ranking import PairwiseLatencyRanker, PairwiseLatencyPrediction

__all__ = [
    "KNOWLEDGE_FIELDS",
    "BehaviorTarget",
    "AdaptiveCalibrationEvidence",
    "BankRelativeEffectModel",
    "BankRelativePrediction",
    "BankRelativeSafetyModel",
    "BankRelativeSafetyPrediction",
    "BankRelativeValidation",
    "Candidate",
    "CandidateEngine",
    "DIRECT_BASE_AUDIT_BANK_WORKLOADS",
    "DIRECT_BASE_AUDIT_PAIRED_RECORDS",
    "DIRECT_BASE_AUDIT_UNIQUE_RECORDS",
    "DIRECT_BASE_AUDIT_WINNER_WORKLOADS",
    "DIRECT_BASE_AUDIT_WORKLOADS",
    "DIRECT_BASE_L2_RESIDENT_RATIO",
    "DIRECT_BASE_RULE_VERSION",
    "DIRECT_RULE_AUDIT_RECORDS",
    "DIRECT_RULE_AUDIT_UNIQUE_RECORDS",
    "DIRECT_RULE_AUDIT_WORKLOADS",
    "DIRECT_RULE_TEMPLATE_AUDIT",
    "GenerationBudget",
    "Hardware",
    "MeasuredObservation",
    "OneShotDecision",
    "PairwiseLatencyPrediction",
    "PairwiseLatencyRanker",
    "RacingPlan",
    "Schedule",
    "SearchConfig",
    "SearchResult",
    "SolverReport",
    "Template",
    "TemplateEvidence",
    "Workload",
    "adaptive_calibration_evidence",
    "plan_template_race",
    "select_adaptive_calibration_candidates",
    "select_calibration_candidates",
    "select_one_shot_candidate",
    "validate_bank_relative_selector",
    "direct_base_candidate",
    "direct_rule_candidate",
]
