#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE=""
PHYSICAL_DEVICE="${PHYSICAL_NPU_ID:-1}"
WARMUP="${OP_NPU_WARMUP:-2}"
SAMPLES="${OP_NPU_SAMPLES:-5}"
# Source-package compilation is deliberately serialized. Do not inherit a
# broad BUILD_JOBS setting from a shared server: eight overlays are built one
# after another and each internal tiling-key compile is also constrained.
BUILD_JOBS=1

usage() {
    cat <<'USAGE'
Usage: ./run_npu.sh --mode full [-d PHYSICAL_NPU_ID]

Runs the source-preserving non-MatMul candidate campaign on one NPU.

Included semantic operators: FlashAttentionScoreGrad,
FusedInferAttentionScore, GatherElements, ScatterElements.
Excluded: MatMul (it has its own historical campaign), Transpose and GatherV2
(no matching 910B original tiling route is available and they are not faked).

Every admitted shape must retain at least 20 distinct, successful,
output-validated tilings. Each collector invokes its complete original source
strategy/dispatcher set with finite AIV/AIC budgets 1..20. Only if that set is
below 20 raw identities may its declared source-visible capacity envelope be
used (L2 for FASG; UB for the other three). Strategy code, predicates,
kernels, and generated tiling fields are never manually edited. The audit-only
passthrough records the identity generated by the original dispatcher.

The repository ships pinned, uncompiled source snapshots for the four source
overlays. ``full`` unpacks them only under profiling/.source_cache/ and then
builds the modified host tilers on the selected NPU host. It makes no network
request and does not read or write /home/CCE_EXTRACT. Its GatherElements
compatibility port is labelled and can admit data only after exact real-NPU
output comparison.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode) MODE="${2:?missing value for --mode}"; shift 2 ;;
        -d|--device) PHYSICAL_DEVICE="${2:?missing physical NPU ID}"; shift 2 ;;
        --warmup) WARMUP="${2:?missing warmup count}"; shift 2 ;;
        --samples) SAMPLES="${2:?missing sample count}"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "fatal: unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [[ "${MODE}" != "full" ]]; then
    echo "fatal: only --mode full is supported" >&2
    exit 2
fi
for value_name in PHYSICAL_DEVICE WARMUP SAMPLES; do
    value="${!value_name}"
    if ! [[ "${value}" =~ ^[0-9]+$ ]]; then
        echo "fatal: ${value_name} must be a non-negative integer" >&2
        exit 2
    fi
done
if (( SAMPLES < 1 )); then
    echo "fatal: samples must be at least 1" >&2
    exit 2
fi
if [[ ! -e "/dev/davinci${PHYSICAL_DEVICE}" ]]; then
    echo "fatal: physical NPU device node is absent: /dev/davinci${PHYSICAL_DEVICE}" >&2
    exit 1
fi

CANN_ROOT="${CANN_ROOT:-/usr/local/Ascend/ascend-toolkit/latest}"
if [[ ! -d "${CANN_ROOT}" || ! -f "${CANN_ROOT}/opp/version.info" ]]; then
    echo "fatal: CANN root or its OPP package is missing: ${CANN_ROOT}" >&2
    exit 1
fi
ENV_FILE=""
for candidate in "${CANN_ROOT}/set_env.sh" "$(dirname "${CANN_ROOT}")/set_env.sh"; do
    if [[ -f "${candidate}" ]]; then ENV_FILE="${candidate}"; break; fi
done
if [[ -z "${ENV_FILE}" ]]; then
    echo "fatal: CANN environment script is missing under ${CANN_ROOT}" >&2
    exit 1
fi
set +u
source "${ENV_FILE}"
set -u
export ASCEND_HOME_PATH="${CANN_ROOT}"
export ASCEND_TOOLKIT_HOME="${CANN_ROOT}"
export ASCEND_OPP_PATH="${CANN_ROOT}/opp"
export ASCEND_RT_VISIBLE_DEVICES="${PHYSICAL_DEVICE}"
export TILINGKEY_PAR_COMPILE=1
export OMP_NUM_THREADS=1
unset ASCEND_CUSTOM_OPP_PATH ASCENDC_CPU_DEBUG

# Each checkout owns its source cache. The source snapshots are repository
# inputs, not network fetches and not shared-server dependencies.
PRIVATE_SOURCE_CACHE="${ROOT}/.source_cache/repo_bundles_v1"
mkdir -p "${PRIVATE_SOURCE_CACHE}"

prepare_repo_source() {
    local kind="$1"
    local destination="$2"
    if [[ -f "${destination}/.source_bundle_attestation.json" ]]; then return; fi
    if [[ -e "${destination}" ]]; then
        echo "fatal: private repository-source cache is incomplete: ${destination}" >&2
        exit 2
    fi
    echo "SOURCE_PREPARE {\"source\":\"${kind}\",\"destination\":\"${destination}\",\"scope\":\"this_profiling_checkout_only\",\"network_calls\":0}"
    python3 "${ROOT}/source_adapter/materialize_repo_source_bundle.py" --kind "${kind}" --destination "${destination}"
}

ADV_SOURCE="${PRIVATE_SOURCE_CACHE}/cann_ops_adv"
OPS_SOURCE="${PRIVATE_SOURCE_CACHE}/cann_ops"
GATHER_EXTRACT_SOURCE="${PRIVATE_SOURCE_CACHE}/gather_elements_v2"
prepare_repo_source cann_ops_adv "${ADV_SOURCE}"
prepare_repo_source cann_ops "${OPS_SOURCE}"
prepare_repo_source gather_elements_v2 "${GATHER_EXTRACT_SOURCE}"

SOURCE_ID="$({
    sha256sum \
        "${ROOT}/multi_op_bench/CMakeLists.txt" \
        "${ROOT}/multi_op_bench/runner.cpp" \
        "${ROOT}/source_adapter/non_matmul_source_lock.json" \
        "${ROOT}/source_adapter/non_matmul_candidate_catalog.py" \
        "${ROOT}/source_adapter/prepare_fasg_strategy_overlays.py" \
        "${ROOT}/source_adapter/prepare_fias_source_overlay.py" \
        "${ROOT}/source_adapter/prepare_gather_elements_compat_overlay.py" \
        "${ROOT}/source_adapter/prepare_scatter_source_overlay.py" \
        "${ROOT}/source_adapter/build_source_candidate_overlay.py" \
        "${ROOT}/source_adapter/materialize_repo_source_bundle.py" \
        "${ROOT}/source_adapter/materialize_installed_dynamic_opp.py" \
        "${ROOT}/source_adapter/run_non_matmul_candidate_campaign.py"
    sha256sum "${ROOT}/source_adapter/vendor_source/cann_ops_8_1rc1.tar.gz" \
        "${ROOT}/source_adapter/vendor_source/cann_ops_adv_8_1rc1.tar.gz" \
        "${ROOT}/source_adapter/vendor_source/gather_elements_v2_source.zip"
    readlink -f "${CANN_ROOT}"
    sha256sum "${GATHER_EXTRACT_SOURCE}/op_host/gather_elements_v2_tiling.cpp"
} | sha256sum | cut -c1-20)"
STATE="${ROOT}/.benchmark_state/non_matmul_source_candidate_v5/${SOURCE_ID}"
OVERLAY_PARENT="${STATE}/overlays"
PACKAGE_BUILD_PARENT="${STATE}/package_builds"
CUSTOM_OPP_PARENT="${STATE}/custom_opp"
RUNNER_BUILD="${STATE}/runner_build"
RESULTS="${ROOT}/results/non_matmul_source_candidate_v5/${SOURCE_ID}"
PROGRESS="${RESULTS}/progress.jsonl"
mkdir -p "${OVERLAY_PARENT}" "${PACKAGE_BUILD_PARENT}" "${CUSTOM_OPP_PARENT}" "${RUNNER_BUILD}" "${RESULTS}"

echo "Non-MatMul original-source tiling candidate campaign"
echo "  target:             physical NPU ${PHYSICAL_DEVICE} -> worker logical NPU 0"
echo "  source:             ${ADV_SOURCE}"
echo "  build harness:      ${OPS_SOURCE} (pinned public CMake framework)"
echo "  Gather source:      ${GATHER_EXTRACT_SOURCE} (attested CANN-8.3 source; 8.1 CMake compatibility only)"
echo "  operators:          FlashAttentionScoreGrad, FusedInferAttentionScore, GatherElements, ScatterElements"
echo "  excluded:           MatMul; Transpose/GatherV2 without matching original 910B source route"
echo "  semantic workloads: about 1,200 reviewed deterministic legal geometries"
echo "  source search:      every original dispatcher/strategy × source AIV caps 1..20; capacity heuristics only after that set is below 20 identities"
echo "  formal group gate:  at least 20 distinct, successful, output-validated tilings per shape; complete groups only"
echo "  formal data target: at most 20,000 output-validated device-event latency records"
echo "  measurement:        ${WARMUP} warmups + ${SAMPLES} device-event samples; no host timeout/kill"
echo "  build pressure:      one source host-tiler build at a time; installed dynamic device source compiles only an actually launched key"
echo "  output:             ${PROGRESS} (JSONL only; temporary full references under /tmp)"
echo "  resume:             admitted/rejected workload groups are never rerun; only incomplete groups resume"

python3 "${ROOT}/source_adapter/non_matmul_candidate_catalog.py" --audit | sed 's/^/SOURCE_CANDIDATE_CATALOG /'

FASG_BATCH="${STATE}/fasg_overlay_batch.json"
if [[ ! -f "${FASG_BATCH}" ]]; then
    mkdir -p "${OVERLAY_PARENT}/fasg"
    echo "SOURCE_OVERLAY_PREPARE_BEGIN strategies=8"
    if ! python3 "${ROOT}/source_adapter/prepare_fasg_strategy_overlays.py" \
        --source-root "${ADV_SOURCE}" --harness-root "${OPS_SOURCE}" \
        --output-parent "${OVERLAY_PARENT}/fasg" >"${FASG_BATCH}" 2>"${STATE}/fasg_overlay_prepare.log"; then
        tail -80 "${STATE}/fasg_overlay_prepare.log" >&2 || true
        exit 1
    fi
    echo "SOURCE_OVERLAY_PREPARE_END strategies=8"
fi

shopt -s nullglob
overlay_manifests=("${OVERLAY_PARENT}"/fasg/fasg_*/source_candidate_overlay.json)
shopt -u nullglob
if (( ${#overlay_manifests[@]} != 8 )); then
    echo "fatal: expected exactly 8 verified FASG overlays, found ${#overlay_manifests[@]}" >&2
    exit 1
fi

FIAS_OVERLAY="${OVERLAY_PARENT}/fias/fias_source_dispatch/source_candidate_overlay.json"
if [[ ! -f "${FIAS_OVERLAY}" ]]; then
    mkdir -p "${OVERLAY_PARENT}/fias"
    if ! python3 "${ROOT}/source_adapter/prepare_fias_source_overlay.py" --source-root "${ADV_SOURCE}" --harness-root "${OPS_SOURCE}" \
        --output-parent "${OVERLAY_PARENT}/fias" >"${STATE}/fias_overlay_batch.json" 2>"${STATE}/fias_overlay_prepare.log"; then
        tail -80 "${STATE}/fias_overlay_prepare.log" >&2 || true
        exit 1
    fi
fi

GATHER_OVERLAY="${OVERLAY_PARENT}/gather/gather_elements_v2_compat_source/source_candidate_overlay.json"
if [[ ! -f "${GATHER_OVERLAY}" ]]; then
    mkdir -p "${OVERLAY_PARENT}/gather"
    if ! python3 "${ROOT}/source_adapter/prepare_gather_elements_compat_overlay.py" --parent-source-root "${OPS_SOURCE}" \
        --extracted-source-root "${GATHER_EXTRACT_SOURCE}" --output-parent "${OVERLAY_PARENT}/gather" >"${STATE}/gather_overlay_batch.json" 2>"${STATE}/gather_overlay_prepare.log"; then
        tail -80 "${STATE}/gather_overlay_prepare.log" >&2 || true
        exit 1
    fi
fi

SCATTER_OVERLAY="${OVERLAY_PARENT}/scatter/scatter_elements_v2_source/source_candidate_overlay.json"
if [[ ! -f "${SCATTER_OVERLAY}" ]]; then
    mkdir -p "${OVERLAY_PARENT}/scatter"
    if ! python3 "${ROOT}/source_adapter/prepare_scatter_source_overlay.py" --source-root "${OPS_SOURCE}" \
        --output-parent "${OVERLAY_PARENT}/scatter" >"${STATE}/scatter_overlay_batch.json" 2>"${STATE}/scatter_overlay_prepare.log"; then
        tail -80 "${STATE}/scatter_overlay_prepare.log" >&2 || true
        exit 1
    fi
fi

overlay_manifests+=("${FIAS_OVERLAY}" "${GATHER_OVERLAY}" "${SCATTER_OVERLAY}")
candidate_manifest_args=()

label_for_overlay() {
    python3 -c 'import json,sys; m=json.load(open(sys.argv[1], encoding="utf-8")); print((m["cmake_op_name"] + "__" + (m.get("strategy_class") or "dispatch")).lower())' "$1"
}

for overlay_manifest in "${overlay_manifests[@]}"; do
    overlay="$(dirname "${overlay_manifest}")"
    label="$(label_for_overlay "${overlay_manifest}")"
    build_dir="${PACKAGE_BUILD_PARENT}/${label}_host"
    build_manifest="${build_dir}/source_candidate_build.json"
    build_log="${STATE}/${label}_host_tiler_build.log"
    if [[ ! -f "${build_manifest}" ]]; then
        if [[ -e "${build_dir}" ]]; then
            echo "fatal: incomplete source host-tiler build exists and is intentionally not overwritten: ${build_dir}" >&2
            echo "       inspect ${build_log}; remove only that explicit build directory before rerunning." >&2
            exit 1
        fi
        echo "SOURCE_HOST_TILER_BUILD_BEGIN source=${label}"
        if ! python3 "${ROOT}/source_adapter/build_source_candidate_overlay.py" \
            --overlay "${overlay}" --build-dir "${build_dir}" --cann-root "${CANN_ROOT}" \
            --target optiling --jobs "${BUILD_JOBS}" >"${build_log}" 2>&1; then
            tail -100 "${build_log}" >&2 || true
            exit 1
        fi
        echo "SOURCE_HOST_TILER_BUILD_END source=${label}"
    fi
    custom_root="${CUSTOM_OPP_PARENT}/${label}"
    custom_manifest="${custom_root}/source_candidate_package.json"
    materialize_log="${STATE}/${label}_dynamic_opp_materialize.log"
    if [[ ! -f "${custom_manifest}" ]]; then
        if [[ -e "${custom_root}" ]]; then
            if [[ -n "$(find "${custom_root}" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
                echo "fatal: incomplete isolated dynamic custom OPP root exists and is intentionally not merged: ${custom_root}" >&2
                exit 1
            fi
        else
            mkdir -p "${custom_root}"
        fi
        echo "SOURCE_DYNAMIC_OPP_MATERIALIZE_BEGIN source=${label}"
        if ! python3 "${ROOT}/source_adapter/materialize_installed_dynamic_opp.py" \
            --build-manifest "${build_manifest}" --installed-op-impl "${CANN_ROOT}/opp/built-in/op_impl" \
            --destination "${custom_root}" >"${materialize_log}" 2>&1; then
            tail -100 "${materialize_log}" >&2 || true
            exit 1
        fi
        echo "SOURCE_DYNAMIC_OPP_MATERIALIZE_END source=${label}"
    fi
    candidate_manifest_args+=(--custom-opp-manifest "${custom_manifest}")
done
if (( ${#candidate_manifest_args[@]} != 22 )); then
    echo "fatal: expected eleven source host-tiler roots, found $((${#candidate_manifest_args[@]} / 2))" >&2
    exit 1
fi

cmake -S "${ROOT}/multi_op_bench" -B "${RUNNER_BUILD}" \
    -DCMAKE_BUILD_TYPE=Release -DASCEND_CANN_PACKAGE_PATH="${CANN_ROOT}"
cmake --build "${RUNNER_BUILD}" --target multi_op_npu_runner --parallel "${BUILD_JOBS}"

PYTHONPATH="${ROOT}/multi_op_bench" python3 "${ROOT}/source_adapter/run_non_matmul_candidate_campaign.py" \
    --runner "${RUNNER_BUILD}/multi_op_npu_runner" --progress "${PROGRESS}" \
    --device 0 --warmup "${WARMUP}" --samples "${SAMPLES}" \
    "${candidate_manifest_args[@]}"
