#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE=""
PHYSICAL_DEVICE="${PHYSICAL_NPU_ID:-1}"
WARMUP="${OP_NPU_WARMUP:-2}"
SAMPLES="${OP_NPU_SAMPLES:-5}"
# Source-package compilation is deliberately serialized. Do not inherit a
# broad BUILD_JOBS setting from a shared server: eight overlays are built one
# after another and each internal tiling-key compile is also constrained.
BUILD_JOBS=1

usage() {
    cat <<'USAGE'
Usage: ./run_npu.sh --mode full [-d PHYSICAL_NPU_ID]

Runs the source-preserving non-MatMul candidate campaign on one NPU.

Included semantic operators: FlashAttentionScoreGrad,
FusedInferAttentionScore, GatherElements, ScatterElements.
Excluded: MatMul (it has its own historical campaign), Transpose and GatherV2
(no matching 910B original tiling route is available and they are not faked).

FlashAttentionScoreGrad is run once per each of the eight strategies actually
registered by the pinned official CANN 8.1.RC1 source. Every strategy is built
as a separate custom-OPP package with only its original registration enabled;
the strategy code, predicates, and kernel are unchanged. A common audit-only
passthrough records the identity already generated by the original dispatcher,
then returns its unchanged status. A
strategy is retained only if it succeeds on the original context and its full
dq/dk/dv result matches the installed-operator reference.

The original source must already be available outside this Git repository.
Set CANN_OPS_ADV_SOURCE=/path/to/pinned/cann-ops-adv-8.1rc1. The exact
one-time source fetch command is printed if it is missing.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode) MODE="${2:?missing value for --mode}"; shift 2 ;;
        -d|--device) PHYSICAL_DEVICE="${2:?missing physical NPU ID}"; shift 2 ;;
        --warmup) WARMUP="${2:?missing warmup count}"; shift 2 ;;
        --samples) SAMPLES="${2:?missing sample count}"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "fatal: unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [[ "${MODE}" != "full" ]]; then
    echo "fatal: only --mode full is supported" >&2
    exit 2
fi
for value_name in PHYSICAL_DEVICE WARMUP SAMPLES; do
    value="${!value_name}"
    if ! [[ "${value}" =~ ^[0-9]+$ ]]; then
        echo "fatal: ${value_name} must be a non-negative integer" >&2
        exit 2
    fi
done
if (( SAMPLES < 1 )); then
    echo "fatal: samples must be at least 1" >&2
    exit 2
fi
if [[ ! -e "/dev/davinci${PHYSICAL_DEVICE}" ]]; then
    echo "fatal: physical NPU device node is absent: /dev/davinci${PHYSICAL_DEVICE}" >&2
    exit 1
fi

CANN_ROOT="${CANN_ROOT:-/usr/local/Ascend/ascend-toolkit/latest}"
if [[ ! -d "${CANN_ROOT}" || ! -f "${CANN_ROOT}/opp/version.info" ]]; then
    echo "fatal: CANN root or its OPP package is missing: ${CANN_ROOT}" >&2
    exit 1
fi
ENV_FILE=""
for candidate in "${CANN_ROOT}/set_env.sh" "$(dirname "${CANN_ROOT}")/set_env.sh"; do
    if [[ -f "${candidate}" ]]; then ENV_FILE="${candidate}"; break; fi
done
if [[ -z "${ENV_FILE}" ]]; then
    echo "fatal: CANN environment script is missing under ${CANN_ROOT}" >&2
    exit 1
fi
set +u
source "${ENV_FILE}"
set -u
export ASCEND_HOME_PATH="${CANN_ROOT}"
export ASCEND_TOOLKIT_HOME="${CANN_ROOT}"
export ASCEND_OPP_PATH="${CANN_ROOT}/opp"
export ASCEND_RT_VISIBLE_DEVICES="${PHYSICAL_DEVICE}"
export TILINGKEY_PAR_COMPILE=1
export OMP_NUM_THREADS=1
unset ASCEND_CUSTOM_OPP_PATH ASCENDC_CPU_DEBUG

# Source preparation is deliberately separate from this run: a measurement
# must never silently download a different source tree. The collector itself
# checks the exact pinned commit and source hashes before creating overlays.
ADV_SOURCE="${CANN_OPS_ADV_SOURCE:-}"
if [[ -z "${ADV_SOURCE}" ]]; then
    for candidate in \
        "/usr/local/Ascend/.source_cache/cann-ops-adv-8.1rc1" \
        "/home/CCE_EXTRACT/cann-ops-adv-8.1rc1"; do
        if [[ -d "${candidate}/.git" ]]; then ADV_SOURCE="${candidate}"; break; fi
    done
fi
if [[ -z "${ADV_SOURCE}" || ! -d "${ADV_SOURCE}/.git" ]]; then
    echo "fatal: pinned official cann-ops-adv source is not available." >&2
    echo "one-time preparation (outside this repository):" >&2
    echo "  python3 ${ROOT}/source_adapter/fetch_official_cann_ops_adv.py --destination /path/outside/profiling/cann-ops-adv-8.1rc1" >&2
    echo "then rerun with: CANN_OPS_ADV_SOURCE=/path/outside/profiling/cann-ops-adv-8.1rc1 ./run_npu.sh --mode full -d ${PHYSICAL_DEVICE}" >&2
    exit 2
fi

SOURCE_ID="$({
    sha256sum \
        "${ROOT}/multi_op_bench/CMakeLists.txt" \
        "${ROOT}/multi_op_bench/runner.cpp" \
        "${ROOT}/source_adapter/non_matmul_source_lock.json" \
        "${ROOT}/source_adapter/non_matmul_candidate_catalog.py" \
        "${ROOT}/source_adapter/prepare_fasg_strategy_overlays.py" \
        "${ROOT}/source_adapter/build_fasg_strategy_overlay.py" \
        "${ROOT}/source_adapter/install_fasg_strategy_package.py" \
        "${ROOT}/source_adapter/run_non_matmul_candidate_campaign.py"
    git -C "${ADV_SOURCE}" rev-parse HEAD
    readlink -f "${CANN_ROOT}"
} | sha256sum | cut -c1-20)"
STATE="${ROOT}/.benchmark_state/non_matmul_source_candidate_v1/${SOURCE_ID}"
OVERLAY_PARENT="${STATE}/fasg_overlays"
PACKAGE_BUILD_PARENT="${STATE}/fasg_package_builds"
CUSTOM_OPP_PARENT="${STATE}/fasg_custom_opp"
RUNNER_BUILD="${STATE}/runner_build"
RESULTS="${ROOT}/results/non_matmul_source_candidate_v1/${SOURCE_ID}"
PROGRESS="${RESULTS}/progress.jsonl"
mkdir -p "${OVERLAY_PARENT}" "${PACKAGE_BUILD_PARENT}" "${CUSTOM_OPP_PARENT}" "${RUNNER_BUILD}" "${RESULTS}"

echo "Non-MatMul original-source tiling candidate campaign"
echo "  target:             physical NPU ${PHYSICAL_DEVICE} -> worker logical NPU 0"
echo "  source:             ${ADV_SOURCE}"
echo "  operators:          FlashAttentionScoreGrad, FusedInferAttentionScore, GatherElements, ScatterElements"
echo "  excluded:           MatMul; Transpose/GatherV2 without matching original 910B source route"
echo "  semantic workloads: 207 explicit deterministic geometries"
echo "  FASG candidates:    8 original registered source strategies; exact raw identities are deduplicated before timing"
echo "  record ceiling:      20,000 (current source-derived plan maximum: 711 result rows)"
echo "  measurement:        ${WARMUP} warmups + ${SAMPLES} device-event samples; no host timeout/kill"
echo "  build pressure:      one package build and one tiling-key compile at a time"
echo "  output:             ${PROGRESS} (JSONL only; temporary full references under /tmp)"
echo "  resume:             all terminal exact candidate records are never rerun; a deliberate retry uses a new result path"

python3 "${ROOT}/source_adapter/non_matmul_candidate_catalog.py" --audit | sed 's/^/SOURCE_CANDIDATE_CATALOG /'

OVERLAY_BATCH="${STATE}/fasg_overlay_batch.json"
if [[ ! -f "${OVERLAY_BATCH}" ]]; then
    echo "SOURCE_OVERLAY_PREPARE_BEGIN strategies=8"
    if ! python3 "${ROOT}/source_adapter/prepare_fasg_strategy_overlays.py" \
        --source-root "${ADV_SOURCE}" --output-parent "${OVERLAY_PARENT}" >"${OVERLAY_BATCH}" 2>"${STATE}/overlay_prepare.log"; then
        tail -80 "${STATE}/overlay_prepare.log" >&2 || true
        exit 1
    fi
    echo "SOURCE_OVERLAY_PREPARE_END strategies=8"
fi

shopt -s nullglob
overlay_manifests=("${OVERLAY_PARENT}"/fasg_*/source_candidate_overlay.json)
shopt -u nullglob
if (( ${#overlay_manifests[@]} != 8 )); then
    echo "fatal: expected exactly 8 verified FASG overlays, found ${#overlay_manifests[@]}" >&2
    exit 1
fi

candidate_manifest_args=()
for overlay_manifest in "${overlay_manifests[@]}"; do
    overlay="$(dirname "${overlay_manifest}")"
    label="$(basename "${overlay}")"
    build_dir="${PACKAGE_BUILD_PARENT}/${label}"
    build_manifest="${build_dir}/source_candidate_build.json"
    package_log="${STATE}/${label}_package_build.log"
    if [[ ! -f "${build_manifest}" ]]; then
        if [[ -e "${build_dir}" ]]; then
            echo "fatal: incomplete package build exists and is intentionally not overwritten: ${build_dir}" >&2
            echo "       inspect ${package_log}; remove only that explicit build directory before rerunning." >&2
            exit 1
        fi
        echo "SOURCE_PACKAGE_BUILD_BEGIN strategy=${label}"
        if ! python3 "${ROOT}/source_adapter/build_fasg_strategy_overlay.py" \
            --overlay "${overlay}" --build-dir "${build_dir}" --cann-root "${CANN_ROOT}" \
            --target package --jobs "${BUILD_JOBS}" >"${package_log}" 2>&1; then
            tail -100 "${package_log}" >&2 || true
            exit 1
        fi
        echo "SOURCE_PACKAGE_BUILD_END strategy=${label}"
    fi
    custom_root="${CUSTOM_OPP_PARENT}/${label}"
    custom_manifest="${custom_root}/fasg_source_candidate_package.json"
    install_log="${STATE}/${label}_package_install.log"
    if [[ ! -f "${custom_manifest}" ]]; then
        if [[ -e "${custom_root}" ]]; then
            if [[ -n "$(find "${custom_root}" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
                echo "fatal: incomplete isolated custom OPP root exists and is intentionally not merged: ${custom_root}" >&2
                exit 1
            fi
        else
            mkdir -p "${custom_root}"
        fi
        echo "SOURCE_PACKAGE_INSTALL_BEGIN strategy=${label}"
        if ! python3 "${ROOT}/source_adapter/install_fasg_strategy_package.py" \
            --build-manifest "${build_manifest}" --destination "${custom_root}" >"${install_log}" 2>&1; then
            tail -80 "${install_log}" >&2 || true
            exit 1
        fi
        echo "SOURCE_PACKAGE_INSTALL_END strategy=${label}"
    fi
    candidate_manifest_args+=(--fasg-custom-opp-manifest "${custom_manifest}")
done

cmake -S "${ROOT}/multi_op_bench" -B "${RUNNER_BUILD}" \
    -DCMAKE_BUILD_TYPE=Release -DASCEND_CANN_PACKAGE_PATH="${CANN_ROOT}"
cmake --build "${RUNNER_BUILD}" --target multi_op_npu_runner --parallel "${BUILD_JOBS}"

PYTHONPATH="${ROOT}/multi_op_bench" python3 "${ROOT}/source_adapter/run_non_matmul_candidate_campaign.py" \
    --runner "${RUNNER_BUILD}/multi_op_npu_runner" --progress "${PROGRESS}" \
    --device 0 --warmup "${WARMUP}" --samples "${SAMPLES}" \
    "${candidate_manifest_args[@]}"
