#!/usr/bin/env python3
"""Create source-rule candidate overlays for FlashAttentionScoreGrad.

Each overlay is a new git worktree at the pinned public source revision.  It
keeps exactly one original `REGISTER_TILING_TEMPLATE` registration and disables
the other registrations. No strategy class, predicate, kernel, or generated
tiling field is changed. The collector may bound the source compile-info
AIV/AIC core budget through ``FASG_SOURCE_AIV_CAP`` before the original
strategy runs. The matching AIC budget is derived from the platform's original
AIC:AIV ratio. This is a finite source-input candidate axis, not a hand-built
tiling or a mutation of raw tiling after source generation. If that complete
original-source collection has fewer than the required distinct tilings, a
separately labelled L2-envelope divisor may reduce only the source-visible L2
scheduling budget. The resulting tile still has to fit the actual, larger
physical L2 and is generated by the original source calculation.

The FASG entry has one audit-only status passthrough: after the original
dispatcher returns, it records the already-generated raw tiling identity only
when a temporary audit-path environment variable is set. It never changes the
context or return status. Therefore a failed overlay means that the chosen
original strategy rejected that source context; it is not converted into a
synthetic candidate.

The public 8.1 advanced tree intentionally has no top-level CMakeLists.txt.
For an executable package it therefore receives an attested build harness
derived from the pinned public ``cann-ops`` root CMake file, changing only its
``src/common`` utility path to this tree's ``src/utils`` path.  This harness
does not alter tiler/kernel source.  This script only creates source overlays
and JSON manifests.  It neither downloads source nor compiles, launches,
resets, or otherwise calls an NPU.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent
LOCK_PATH = Path(os.environ.get("CANN81_SOURCE_LOCK", str(ROOT / "non_matmul_source_lock.json")))
LOCK = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
OP = LOCK["operators"]["flash_attention_score_grad"]
SOURCE = LOCK["sources"]["cann_ops_adv"]
HARNESS_SOURCE = LOCK["sources"]["cann_ops"]
MACRO = OP["registration_macro"]
OPERATOR = OP["registration_operator"]
ENTRY_RELATIVE = Path(OP["relative_root"]) / "ophost/flash_attention_score_grad_tiling.cpp"
AUDIT_SENTINEL = "FASG_SOURCE_TILING_AUDIT_V1"
CORE_BUDGET_SENTINEL = "FASG_SOURCE_AIV_CAP_V1"
L2_ENVELOPE_SENTINEL = "FASG_SOURCE_L2_CAP_V1"
BUILD_SCOPE_SENTINEL = "SOURCE_CANDIDATE_BUILD_SCOPE_V1"
NPU_SUPPORT_FILTER = Path("cmake/util/gen_ops_filter.sh")


# The advanced tree carries the original op-host CMake fragments but no
# top-level project. These are the only source directories admitted to an
# isolated build harness. FIAS keeps its two original dispatcher dependencies
# because its own op-host CMake declares them.
ADVANCED_BUILD_SCOPES = {
    "flash_attention_score_grad": {
        "op_list": ["flash_attention_score_grad"],
        "op_dirs": ["src/transformer/flash_attention_score_grad"],
        "op_host_dirs": ["src/transformer/flash_attention_score_grad/ophost"],
    },
    "fused_infer_attention_score": {
        "op_list": ["fused_infer_attention_score"],
        "op_dirs": [
            "src/transformer/incre_flash_attention",
            "src/transformer/prompt_flash_attention",
            "src/transformer/fused_infer_attention_score",
        ],
        "op_host_dirs": [
            "src/transformer/incre_flash_attention/ophost",
            "src/transformer/prompt_flash_attention/ophost",
            "src/transformer/fused_infer_attention_score/ophost",
        ],
    },
}


def source_build_harness(harness_root: Path, cmake_op_name: str) -> tuple[str, dict[str, object]]:
    """Return the only permitted CMake harness for the source-only adv tree.

    The advanced 8.1 checkout lacks a root CMakeLists.txt but carries original
    op-host CMake fragments. The harness uses the pinned public 8.1 framework
    and explicitly includes only the requested original fragments (plus FIAS'
    declared original dependencies). This prevents the public nested
    ``prepare.sh`` helper from compiling the whole source tree. No source
    rule, tiling field, or kernel algorithm is introduced by this harness.
    """
    require_repo_source_bundle(harness_root, "cann_ops", HARNESS_SOURCE["commit"])
    source_path = harness_root / "CMakeLists.txt"
    if not source_path.is_file() or digest(source_path) != HARNESS_SOURCE["build_harness_cmake_sha256"]:
        raise RuntimeError("pinned public build-harness CMakeLists.txt is absent or mismatched")
    filter_script = harness_root / NPU_SUPPORT_FILTER
    if not filter_script.is_file():
        raise RuntimeError("pinned public build-harness lacks its npu-supported-ops filter")
    scope = ADVANCED_BUILD_SCOPES.get(cmake_op_name)
    if scope is None:
        raise RuntimeError("unsupported advanced source build scope: {}".format(cmake_op_name))
    original = source_path.read_text(encoding="utf-8")
    transformed = original.replace(
        "${CMAKE_CURRENT_SOURCE_DIR}/src/common/src/fallback_comm.cpp",
        "${CMAKE_CURRENT_SOURCE_DIR}/src/utils/src/fallback_comm.cpp",
    ).replace("add_subdirectory(src/common)", "add_subdirectory(src/utils)")
    # The advanced 8.1 CMake helpers predate the public root's final
    # npu-supported-ops packaging helper. Attach that exact generic helper to
    # the generated root harness only; it has no relation to tiling or kernels.
    helper_anchor = "include(cmake/intf.cmake)\n"
    helper = '''include(cmake/intf.cmake)

# SOURCE_CANDIDATE_BUILD_SCOPE_V1: structural packaging helper copied from
# the pinned public CANN-8.1 build framework.
function(add_npu_support_target)
    cmake_parse_arguments(NPUSUP "" "TARGET;OPS_INFO_DIR;OUT_DIR;INSTALL_DIR" "" ${ARGN})
    add_custom_command(OUTPUT ${NPUSUP_OUT_DIR}/npu_supported_ops.json
        COMMAND mkdir -p ${NPUSUP_OUT_DIR}
        COMMAND ${CMAKE_SOURCE_DIR}/cmake/util/gen_ops_filter.sh
                ${NPUSUP_OPS_INFO_DIR}
                ${NPUSUP_OUT_DIR}
    )
    add_custom_target(npu_supported_ops ALL
        DEPENDS ${NPUSUP_OUT_DIR}/npu_supported_ops.json
    )
    install(FILES ${NPUSUP_OUT_DIR}/npu_supported_ops.json
        DESTINATION ${NPUSUP_INSTALL_DIR}
    )
endfunction()

# The advanced source calls its build-tree directory ASCEND_AUTOGEN_DIR while
# the pinned public root's package helper calls it ASCEND_AUTOGEN_PATH.  Alias
# the two names for this detached build only.  The framework type and vendor
# spelling are likewise public packaging metadata, not operator/tiler inputs.
set(ASCEND_AUTOGEN_PATH ${ASCEND_AUTOGEN_DIR})
set(ASCEND_FRAMEWORK_TYPE tensorflow)
set(vendor_name ${VENDOR_NAME})
'''
    if transformed.count(helper_anchor) != 1:
        raise RuntimeError("cannot locate public build-harness helper insertion anchor")
    transformed = transformed.replace(helper_anchor, helper)
    original_scope = '''set(OP_LIST)
set(OP_DIR_LIST)
op_add_subdirectory(OP_LIST OP_DIR_LIST)

foreach (OP_DIR ${OP_DIR_LIST})
    add_subdirectory(${OP_DIR})
endforeach ()

set(OP_DEPEND_DIR_LIST)
op_add_depend_directory(
        OP_LIST ${OP_LIST}
        OP_DIR_LIST OP_DEPEND_DIR_LIST
)
foreach (OP_DEPEND_DIR ${OP_DEPEND_DIR_LIST})
    add_subdirectory(${OP_DEPEND_DIR})
endforeach ()'''
    # The public kernel-packaging helper consumes OP_DIR_LIST after CMake has
    # switched to the build directory.  Its normal discovery returns absolute
    # paths; preserve that contract in the narrowed list rather than leaving
    # it as a source-root-relative path.
    scoped_dirs = "\n".join("        ${CMAKE_CURRENT_SOURCE_DIR}/" + item for item in scope["op_dirs"])
    scoped_hosts = "\n".join("        ${CMAKE_CURRENT_SOURCE_DIR}/" + item for item in scope["op_host_dirs"])
    scoped_ops = " ".join(scope["op_list"])
    scoped_replacement = '''# SOURCE_CANDIDATE_BUILD_SCOPE_V1: the advanced source package has no
# root build project. Keep this detached harness to its requested original
# op-host fragments instead of scanning/compiling unrelated source trees.
set(ASCEND_OP_NAME "{name}" CACHE STRING "operators that need to be compiled" FORCE)
set(OP_LIST {ops})
set(OP_DIR_LIST
{dirs}
)
set(OP_DEPEND_DIR_LIST)
set(SOURCE_CANDIDATE_OPHOST_DIR_LIST
{hosts}
)
foreach (SOURCE_CANDIDATE_OPHOST_DIR ${{SOURCE_CANDIDATE_OPHOST_DIR_LIST}})
    add_subdirectory(${{SOURCE_CANDIDATE_OPHOST_DIR}})
endforeach ()'''.format(name=cmake_op_name, ops=scoped_ops, dirs=scoped_dirs, hosts=scoped_hosts)
    if original_scope not in transformed:
        raise RuntimeError("cannot locate public op-directory selection block")
    transformed = transformed.replace(original_scope, scoped_replacement)
    source_install = '''foreach (_op_name ${OP_LIST})
    install(FILES ${ASCEND_IMPL_OUT_DIR}/dynamic/${_op_name}.py
            DESTINATION ${IMPL_DYNAMIC_INSTALL_DIR}
            OPTIONAL
    )
endforeach ()

foreach (_op_name ${OP_LIST})
    install(FILES ${ASCEND_IMPL_OUT_DIR}/dynamic/${_op_name}.cpp
            DESTINATION ${IMPL_DYNAMIC_INSTALL_DIR}
            OPTIONAL
    )
endforeach ()

install(DIRECTORY ${OPS_ADV_UTILS_KERNEL_INC}/
        DESTINATION ${IMPL_INSTALL_DIR}/ascendc/common
)

foreach (op_dir ${OP_DIR_LIST})
    get_filename_component(_op_name "${op_dir}" NAME)

    file(GLOB KERNEL_FILES
            ${op_dir}/op_kernel/*.cpp
            ${op_dir}/op_kernel/*.h
    )

    install(FILES ${KERNEL_FILES}
            DESTINATION ${IMPL_DYNAMIC_INSTALL_DIR}
            OPTIONAL
    )
endforeach ()'''
    binary_only = '''# REMAINING_ATTENTION_CANN81_PRECOMPILED_PACKAGE_V1: source bytes
# remain private build inputs, but the runtime package receives only host
# libraries, metadata and precompiled 910B objects.  Missing keys fail closed
# instead of entering Python/TBE runtime compilation.'''
    if transformed.count(source_install) != 1:
        raise RuntimeError("cannot locate public dynamic-source install block")
    transformed = transformed.replace(source_install, binary_only)
    if transformed == original or "src/common" in transformed or BUILD_SCOPE_SENTINEL not in transformed:
        raise RuntimeError("unexpected public build-harness layout")
    return transformed, {
        "official_url": HARNESS_SOURCE["url"],
        "official_commit": HARNESS_SOURCE["commit"],
        "source_cmake_sha256": HARNESS_SOURCE["build_harness_cmake_sha256"],
        "transformation": "replace src/common utility paths with src/utils, alias public packaging metadata used by the advanced tree, and structurally select only the requested original op-host CMake fragments",
        "build_scope": {"sentinel": BUILD_SCOPE_SENTINEL, "operator": cmake_op_name,
                        "op_host_directories": scope["op_host_dirs"], "structural_only": True},
        "npu_supported_ops_filter": {
            "source_relative": str(NPU_SUPPORT_FILTER),
            "sha256": digest(filter_script),
            "purpose": "required unchanged public packaging helper for npu_supported_ops.json",
        },
        "generated_cmake_sha256": hashlib.sha256(transformed.encode("utf-8")).hexdigest(),
    }


def require_repo_source_bundle(source_root: Path, kind: str, official_commit: str) -> None:
    """Validate one repository-shipped source snapshot before deriving edits."""
    attestation = source_root / ".source_bundle_attestation.json"
    if not attestation.is_file():
        raise RuntimeError("source snapshot lacks repository-bundle attestation: {}".format(source_root))
    try:
        value = json.loads(attestation.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise RuntimeError("source snapshot attestation is invalid: {}".format(error)) from error
    if (value.get("schema") != "repo_source_bundle_v1" or value.get("bundle_kind") != kind or
            value.get("official_commit") != official_commit or value.get("network_calls") != 0):
        raise RuntimeError("source snapshot does not attest pinned {} source".format(kind))
    status = run(["git", "-C", str(source_root), "status", "--porcelain", "--untracked-files=no"])
    if status:
        raise RuntimeError("private source snapshot is modified: {}".format(source_root))


def materialize_build_support_files(output: Path, harness_root: Path | None,
                                    harness_provenance: dict[str, object]) -> None:
    """Copy the one public packaging helper required by the generated root.

    The advanced source carries original op sources but no top-level CMake
    project.  The generated root deliberately reuses the public 8.1 package
    helper, whose command refers to this relative script.  Keeping an exact,
    hashed copy in the detached overlay is a structural build requirement;
    it neither participates in tiling nor changes an operator source file.
    """
    filter_info = harness_provenance.get("npu_supported_ops_filter")
    if not isinstance(filter_info, dict):
        raise RuntimeError("build harness has no npu-supported-ops filter provenance")
    relative = Path(str(filter_info.get("source_relative", "")))
    destination = output / relative
    if destination.exists():
        if not destination.is_file() or digest(destination) != filter_info.get("sha256"):
            raise RuntimeError("existing detached build-support filter differs from pinned public helper")
        return
    if harness_root is None:
        raise RuntimeError("detached build-support filter is missing")
    source = harness_root / relative
    if (not source.is_file() or digest(source) != filter_info.get("sha256")):
        raise RuntimeError("pinned npu-supported-ops filter hash mismatches its provenance")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    destination.chmod(destination.stat().st_mode | 0o111)
    if digest(destination) != filter_info.get("sha256"):
        raise RuntimeError("copied npu-supported-ops filter hash mismatch")


def instrument_entry_source(source: str) -> str:
    """Add an audit record while returning the original dispatcher status."""
    if AUDIT_SENTINEL in source:
        return source
    original = """ASCENDC_EXTERN_C ge::graphStatus TilingFlashAttentionGradScore(gert::TilingContext *context)
{
    if (CheckParams(context) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    if (IsEmptyOutput(context)) {
        FlashAttentionScoreGradTiling flashAttentionScoreGradTiling;
        return flashAttentionScoreGradTiling.RunEmptyTiling(context);
    } else {
        return TilingRegistry::GetInstance().DoTilingImpl(context);
    }
}"""
    replacement = r"""// FASG_SOURCE_TILING_AUDIT_V1: observational only; no tiling state is modified.
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cerrno>

static uint64_t FASGSourceAuditHash(const uint8_t *data, size_t size)
{
    uint64_t value = 1469598103934665603ULL;
    for (size_t index = 0; index < size; ++index) { value ^= data[index]; value *= 1099511628211ULL; }
    return value;
}

static ge::graphStatus FASGSourceAuditResult(gert::TilingContext *context, ge::graphStatus status)
{
    const char *path = std::getenv("FASG_TILING_AUDIT_PATH");
    if (path == nullptr || context == nullptr) { return status; }
    auto *raw = context->GetRawTilingData();
    const size_t rawSize = raw == nullptr ? 0U : raw->GetDataSize();
    const auto *rawBytes = raw == nullptr ? nullptr : static_cast<const uint8_t *>(raw->GetData());
    const uint64_t digest = rawBytes == nullptr ? 0ULL : FASGSourceAuditHash(rawBytes, rawSize);
    const char *coreCap = std::getenv("FASG_SOURCE_AIV_CAP");
    std::FILE *output = std::fopen(path, "a");
    if (output != nullptr) {
        const char *l2Divisor = std::getenv("FASG_SOURCE_L2_DIVISOR");
        std::fprintf(output, "{\"schema\":\"fasg_raw_tiling_observation_v1\",\"status\":%d,\"aiv_core_cap\":\"%s\",\"l2_cap_divisor\":\"%s\",\"tiling_key\":%llu,\"block_dim\":%u,\"raw_bytes\":%llu,\"raw_fnv1a64\":%llu}\n",
                     static_cast<int>(status), coreCap == nullptr ? "runtime" : coreCap,
                     l2Divisor == nullptr ? "1" : l2Divisor,
                     static_cast<unsigned long long>(context->GetTilingKey()),
                     context->GetBlockDim(), static_cast<unsigned long long>(rawSize),
                     static_cast<unsigned long long>(digest));
        std::fclose(output);
    }
    return status;
}

ASCENDC_EXTERN_C ge::graphStatus TilingFlashAttentionGradScore(gert::TilingContext *context)
{
    if (CheckParams(context) != ge::GRAPH_SUCCESS) { return FASGSourceAuditResult(context, ge::GRAPH_FAILED); }
    if (IsEmptyOutput(context)) {
        FlashAttentionScoreGradTiling flashAttentionScoreGradTiling;
        return FASGSourceAuditResult(context, flashAttentionScoreGradTiling.RunEmptyTiling(context));
    }
    return FASGSourceAuditResult(context, TilingRegistry::GetInstance().DoTilingImpl(context));
}"""
    if source.count(original) != 1:
        raise RuntimeError("cannot locate the exact original FASG tiling entry for instrumentation")
    return source.replace(original, replacement)


def instrument_source_core_budget(source: str) -> str:
    """Bound the original tiler's compile-info AIV/AIC input when requested.

    The source strategy still owns every generated tiling field.  Invalid
    inputs fail closed; they never fall back to a default candidate.
    """
    if CORE_BUDGET_SENTINEL in source:
        return source
    original = """    compileInfoPtr->aivNum = ascendcPlatform.GetCoreNumAiv();
    compileInfoPtr->aicNum = ascendcPlatform.GetCoreNumAic();"""
    replacement = r"""    compileInfoPtr->aivNum = ascendcPlatform.GetCoreNumAiv();
    compileInfoPtr->aicNum = ascendcPlatform.GetCoreNumAic();
    // FASG_SOURCE_AIV_CAP_V1: a finite source-input candidate axis. It never
    // edits a tiling after an original strategy has produced it.
    const char *requestedAivText = std::getenv("FASG_SOURCE_AIV_CAP");
    if (requestedAivText != nullptr) {
        errno = 0;
        char *parseEnd = nullptr;
        const unsigned long long requestedAiv = std::strtoull(requestedAivText, &parseEnd, 10);
        const uint64_t runtimeAiv = compileInfoPtr->aivNum;
        const uint64_t runtimeAic = compileInfoPtr->aicNum;
        if (errno != 0 || parseEnd == requestedAivText || *parseEnd != '\0' || requestedAiv == 0ULL ||
            requestedAiv > runtimeAiv || runtimeAiv == 0ULL || runtimeAic == 0ULL || runtimeAic % runtimeAiv != 0ULL) {
            OPS_LOG_E(context, "invalid source AIV cap: %s (runtime aiv=%lu aic=%lu)", requestedAivText,
                      runtimeAiv, runtimeAic);
            return ge::GRAPH_FAILED;
        }
        const uint64_t aicPerAiv = runtimeAic / runtimeAiv;
        compileInfoPtr->aivNum = static_cast<uint64_t>(requestedAiv);
        compileInfoPtr->aicNum = static_cast<uint64_t>(requestedAiv) * aicPerAiv;
    }
    // FASG_SOURCE_L2_CAP_V1: optional hardware-envelope heuristic. A smaller
    // source-visible L2 budget is always no larger than physical L2, so every
    // original-formula tiling produced here remains capacity-feasible on the
    // target. It is intentionally not a claim about measured L2 placement.
    const char *l2DivisorText = std::getenv("FASG_SOURCE_L2_DIVISOR");
    if (l2DivisorText != nullptr) {
        errno = 0;
        char *parseEnd = nullptr;
        const unsigned long long divisor = std::strtoull(l2DivisorText, &parseEnd, 10);
        const uint64_t runtimeL2 = compileInfoPtr->l2CacheSize;
        if (errno != 0 || parseEnd == l2DivisorText || *parseEnd != '\0' ||
            (divisor != 1ULL && divisor != 2ULL && divisor != 4ULL && divisor != 8ULL) ||
            runtimeL2 == 0ULL || runtimeL2 / divisor == 0ULL) {
            OPS_LOG_E(context, "invalid source L2 divisor: %s (runtime l2=%lu)", l2DivisorText, runtimeL2);
            return ge::GRAPH_FAILED;
        }
        compileInfoPtr->l2CacheSize = runtimeL2 / divisor;
    }"""
    if source.count(original) != 1:
        raise RuntimeError("cannot locate original FASG compile-info core assignment")
    return source.replace(original, replacement)


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as source:
        for part in iter(lambda: source.read(1024 * 1024), b""):
            value.update(part)
    return value.hexdigest()


def run(argv: list[str]) -> str:
    result = subprocess.run(argv, capture_output=True, text=True, check=False)
    if result.returncode:
        raise RuntimeError("command failed rc={} argv={} stderr={}".format(
            result.returncode, " ".join(argv), result.stderr.strip()))
    return result.stdout.strip()


@dataclass(frozen=True)
class Registration:
    relative_path: Path
    start: int
    end: int
    source_class: str
    priority: int
    text: str


def find_close(text: str, opening: int) -> int:
    """Return the index one past `);` for a registration macro invocation."""
    depth = 0
    quote: str | None = None
    escaped = False
    for index in range(opening, len(text)):
        char = text[index]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue
        if char in ("'", '\"'):
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                cursor = index + 1
                while cursor < len(text) and text[cursor].isspace():
                    cursor += 1
                if cursor >= len(text) or text[cursor] != ";":
                    raise RuntimeError("registration macro is missing trailing semicolon")
                return cursor + 1
    raise RuntimeError("unterminated registration macro")


def registrations(source_root: Path) -> list[Registration]:
    op_root = source_root / OP["relative_root"] / "ophost"
    start_pattern = re.compile(re.escape(MACRO) + r"\s*\(")
    class_pattern = re.compile(
        r"^" + re.escape(MACRO) + r"\s*\(\s*\"" + re.escape(OPERATOR) +
        r"\"\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([0-9]+)\s*\);$",
        re.DOTALL,
    )
    output: list[Registration] = []
    for path in sorted(op_root.glob("*.cpp")):
        content = path.read_text(encoding="utf-8")
        for match in start_pattern.finditer(content):
            end = find_close(content, content.find("(", match.start()))
            invocation = content[match.start():end]
            parsed = class_pattern.match(invocation.strip())
            if not parsed:
                continue
            output.append(Registration(
                relative_path=path.relative_to(source_root),
                start=match.start(), end=end,
                source_class=parsed.group(1), priority=int(parsed.group(2)), text=invocation,
            ))
    output.sort(key=lambda row: (row.priority, row.source_class), reverse=True)
    return output


def require_pinned_source(source_root: Path) -> list[Registration]:
    require_repo_source_bundle(source_root, "cann_ops_adv", SOURCE["commit"])
    for relative, expected in OP["pinned_files"].items():
        actual = digest(source_root / OP["relative_root"] / relative)
        if actual != expected:
            raise RuntimeError("pinned source hash mismatch: {}".format(relative))
    rows = registrations(source_root)
    if len(rows) != OP["expected_strategy_count"]:
        raise RuntimeError("unexpected original strategy count: expected={} actual={}".format(
            OP["expected_strategy_count"], len(rows)))
    return rows


def overlay_source(text: str, rows: list[Registration], selected: Registration, relative: Path) -> str:
    local = [row for row in rows if row.relative_path == relative]
    for row in sorted(local, key=lambda item: item.start, reverse=True):
        if row == selected:
            continue
        replacement = "/* source-candidate collector disabled registration: {} priority={} */".format(
            row.source_class, row.priority)
        text = text[:row.start] + replacement + text[row.end:]
    return text


def allowed_overlay_source(before: str, rows: list[Registration], selected: Registration,
                           relative: Path) -> str:
    """Return the only permitted source content for one overlay file."""
    after = overlay_source(before, rows, selected, relative)
    if relative == ENTRY_RELATIVE:
        after = instrument_source_core_budget(instrument_entry_source(after))
    return after


def existing_overlay(source_root: Path, output: Path, selected: Registration,
                     rows: list[Registration], harness_text: str,
                     harness_provenance: dict[str, object]) -> dict[str, object] | None:
    """Return a verified existing overlay, or None when it has not been made.

    This makes a stopped source-preparation stage resumable without accepting a
    partially edited worktree. Every registration source, the audit entry, and
    the attested source-build harness must still equal their allowed
    transformations exactly.
    """
    if not output.exists():
        return None
    manifest_path = output / "source_candidate_overlay.json"
    if not manifest_path.is_file():
        raise RuntimeError("existing overlay has no provenance manifest: {}".format(output))
    metadata = json.loads(manifest_path.read_text(encoding="utf-8"))
    required = {
        "source_family": "cann_ops_adv",
        "cmake_op_name": "flash_attention_score_grad",
        "audit_entry_relative": str(ENTRY_RELATIVE),
        "audit_sentinel": AUDIT_SENTINEL,
        "official_commit": SOURCE["commit"],
        "strategy_class": selected.source_class,
        "strategy_priority": selected.priority,
        "strategy_algorithm_changes": False,
        "kernel_algorithm_changes": False,
        "source_compile_info_core_budget_enumeration": True,
        "source_hardware_envelope_heuristic_enumeration": True,
        "hardware_envelope_heuristic": {
            "enabled": True, "environment": "FASG_SOURCE_L2_DIVISOR", "audit_field": "l2_cap_divisor",
            "resource": "source_visible_l2_scheduling_budget", "divisors": [2, 4, 8], "max_anchors": 16,
        },
    }
    if any(metadata.get(key) != value for key, value in required.items()):
        raise RuntimeError("existing overlay provenance does not match requested strategy: {}".format(output))
    affected = {row.relative_path for row in rows} | {ENTRY_RELATIVE}
    for relative in sorted(affected):
        expected = allowed_overlay_source((source_root / relative).read_text(encoding="utf-8"), rows, selected, relative)
        actual = (output / relative).read_text(encoding="utf-8")
        if actual != expected:
            raise RuntimeError("existing overlay source differs outside the allowed registration isolation: {}".format(
                output / relative))
    generated_harness = output / "CMakeLists.txt"
    if not generated_harness.is_file() or generated_harness.read_text(encoding="utf-8") != harness_text:
        raise RuntimeError("existing overlay build harness differs from its pinned allowed transformation: {}".format(
            generated_harness))
    if metadata.get("build_harness") != harness_provenance:
        raise RuntimeError("existing overlay build-harness provenance differs from the pinned source")
    materialize_build_support_files(output, None, harness_provenance)
    metadata["resumed_existing_overlay"] = True
    return metadata


def write_overlay(source_root: Path, output_parent: Path, selected: Registration, rows: list[Registration],
                  harness_root: Path, harness_text: str,
                  harness_provenance: dict[str, object]) -> dict[str, object]:
    output = output_parent / ("fasg_" + selected.source_class.lower())
    existing = existing_overlay(source_root, output, selected, rows, harness_text, harness_provenance)
    if existing is not None:
        return existing
    run(["git", "-C", str(source_root), "worktree", "add", "--detach", str(output), "HEAD"])
    changed: list[dict[str, str]] = []
    affected = {row.relative_path for row in rows} | {ENTRY_RELATIVE}
    for relative in sorted(affected):
        target = output / relative
        before = target.read_text(encoding="utf-8")
        after = allowed_overlay_source(before, rows, selected, relative)
        if before != after:
            target.write_text(after, encoding="utf-8")
            changed.append({
                "path": str(relative),
                "kind": "source_tiling_observation_and_core_budget" if relative == ENTRY_RELATIVE else "registration_isolation",
                "sha256_before": hashlib.sha256(before.encode("utf-8")).hexdigest(),
                "sha256_after": digest(target),
            })
    (output / "CMakeLists.txt").write_text(harness_text, encoding="utf-8")
    materialize_build_support_files(output, harness_root, harness_provenance)
    status = run(["git", "-C", str(output), "status", "--porcelain", "--untracked-files=no"])
    metadata: dict[str, object] = {
        "schema": "fasg_original_strategy_overlay_v1",
        "operator": OPERATOR,
        "source_family": "cann_ops_adv",
        "cmake_op_name": "flash_attention_score_grad",
        "audit_entry_relative": str(ENTRY_RELATIVE),
        "audit_sentinel": AUDIT_SENTINEL,
        "official_url": SOURCE["url"],
        "official_tag": SOURCE["tag"],
        "official_commit": SOURCE["commit"],
        "strategy_class": selected.source_class,
        "strategy_priority": selected.priority,
        "enabled_registration": selected.text,
        "disabled_original_registrations": [
            {"class": row.source_class, "priority": row.priority}
            for row in rows if row != selected
        ],
        "overlay": str(output),
        "source_status": status.splitlines(),
        "modified_registration_files": changed,
        "instrumentation": {
            "enabled": True,
            "audit_schema": "fasg_raw_tiling_observation_v1",
            "audit_environment": "FASG_TILING_AUDIT_PATH",
            "source_budget_environment": "FASG_SOURCE_AIV_CAP",
            "scope": "FASG entry return status plus raw tiling provenance; a finite AIV/AIC source budget and optional smaller L2 scheduling envelope are accepted before the original strategy runs",
            "mechanism": "write one JSON line only when FASG_TILING_AUDIT_PATH is supplied; read FASG_SOURCE_AIV_CAP and optional FASG_SOURCE_L2_DIVISOR only in TilingPrepareForFlashAttentionScoreGrad",
            "mutates_tiling_context": False,
        },
        "strategy_algorithm_changes": False,
        "kernel_algorithm_changes": False,
        "source_compile_info_core_budget_enumeration": True,
        "source_hardware_envelope_heuristic_enumeration": True,
        "hardware_envelope_heuristic": {
            "enabled": True, "environment": "FASG_SOURCE_L2_DIVISOR", "audit_field": "l2_cap_divisor",
            "resource": "source_visible_l2_scheduling_budget", "divisors": [2, 4, 8], "max_anchors": 16,
        },
        "build_scope": harness_provenance["build_scope"],
        "candidate_rule": "run this original strategy for each finite runtime-derived AIV/AIC source budget; only if that complete original-source set is below the group minimum, rerun selected source contexts with the finite L2 divisors 2/4/8. Deduplicate only exact observed raw tiling identities and retain only later output-validated executions",
        "build_harness": harness_provenance,
        "forbidden": LOCK["collection_contract"]["forbidden"],
    }
    (output / "source_candidate_overlay.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--harness-root", required=True, type=Path,
                        help="pinned public cann-ops tree that supplies the missing advanced-tree build harness")
    parser.add_argument("--output-parent", required=True, type=Path,
                        help="existing directory outside this repository")
    parser.add_argument("--strategy", action="append", default=[],
                        help="original strategy class to prepare; repeatable (default: all)")
    args = parser.parse_args()
    if not args.output_parent.is_dir():
        raise RuntimeError("output parent does not exist: {}".format(args.output_parent))
    rows = require_pinned_source(args.source_root)
    harness_text, harness_provenance = source_build_harness(args.harness_root, "flash_attention_score_grad")
    allowed = {row.source_class for row in rows}
    requested = set(args.strategy) if args.strategy else allowed
    unknown = sorted(requested - allowed)
    if unknown:
        raise RuntimeError("unknown original strategy: {}".format(", ".join(unknown)))
    prepared = [write_overlay(args.source_root, args.output_parent, row, rows, args.harness_root, harness_text, harness_provenance)
                for row in rows if row.source_class in requested]
    print(json.dumps({
        "schema": "fasg_original_strategy_overlay_batch_v1",
        "matmul_included": False,
        "prepared_count": len(prepared),
        "original_registered_strategy_count": len(rows),
        "overlays": prepared,
    }, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except RuntimeError as error:
        print("source-candidate error: {}".format(error), file=sys.stderr)
        sys.exit(2)
