#!/usr/bin/env python3
"""Collect complete, output-validated non-MatMul source-tiling groups.

Every formal group retains *all* distinct raw tilings generated by its finite
original-source search. It is admitted only when at least 20 of those
distinct tilings execute and exactly match the installed operator output.
Candidates that fail discovery, exact-output validation, or latency
measurement are rejected individually and never count toward the twenty.
A group is admitted only when its complete remaining successful set fits the
record budget and still has at least twenty members. The source candidate
axes are legal inputs to original tilers; this program never enumerates,
edits, or replays raw tiling fields.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
CATALOG_PATH = ROOT / "non_matmul_candidate_catalog.py"
LOCK = json.loads((ROOT / "non_matmul_source_lock.json").read_text(encoding="utf-8"))
SCHEMA = "non_matmul_source_candidate_measurement_v5"
# The campaign is intentionally append-only so an interrupted physical-NPU
# run can resume without losing its completed groups.  A single log is kept
# below this limit; the next numeric log is opened before an oversized write.
MAX_LOG_BYTES = 50 * 1024 * 1024
OPERATOR_RUNTIME_NAMES = {
    "FlashAttentionScoreGrad": "flash_attention_score_grad",
    "FusedInferAttentionScore": "fused_infer_attention_score",
    "GatherElementsV2": "gather_elements",
    "ScatterElementsV2": "scatter_elements",
}
RUNTIME_OPERATOR_NAMES = {value: key for key, value in OPERATOR_RUNTIME_NAMES.items()}


def digest_file(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def stable_hash(value: Any) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def load_catalog() -> tuple[list[dict[str, Any]], dict[str, Any], Any]:
    spec = importlib.util.spec_from_file_location("non_matmul_candidate_catalog", CATALOG_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load non-MatMul candidate catalog")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    workloads = module.catalog()
    audit = module.audit(workloads)
    if audit.get("matmul_included") or int(audit["formal_latency_target"]) != 20_000:
        raise RuntimeError("catalog violates the non-MatMul 20,000-record contract")
    return workloads, audit, module


def parse_worker_result(output: str) -> dict[str, Any] | None:
    for line in reversed(output.splitlines()):
        marker = "MULTIOP_NPU_RESULT "
        if line.startswith(marker):
            try:
                return json.loads(line[len(marker):])
            except json.JSONDecodeError:
                return None
    return None


def worker_args(runner: Path, workload: dict[str, Any], device: int, warmup: int, samples: int) -> list[str]:
    values = [str(runner), "--workload-id", workload["workload_id"], "--op", workload["op"],
              "--device", str(device), "--warmup", str(warmup), "--samples", str(samples),
              "--expected-soc", "Ascend910B3"]
    if workload["op"] in ("flash_attention_score_grad", "fused_infer_attention_score"):
        fields = ("batch", "q_heads", "kv_heads", "q_seq", "kv_seq", "head_dim", "layout", "dtype")
    elif workload["op"] == "gather_elements":
        fields = ("shape", "index_shape", "axis", "dtype", "index_dtype")
    elif workload["op"] == "scatter_elements":
        fields = ("shape", "index_shape", "axis", "dtype", "index_dtype", "reduce")
    else:
        raise RuntimeError("unsupported runtime op: {}".format(workload["op"]))
    for field in fields:
        item = workload[field]
        rendered = ",".join(map(str, item)) if isinstance(item, list) else str(item)
        values += ["--" + field.replace("_", "-"), rendered]
    return values


def run_worker(arguments: list[str], environment: dict[str, str]) -> tuple[dict[str, Any], str, float, int]:
    # No subprocess timeout: a forced host kill can poison a real device task.
    started = time.monotonic()
    done = subprocess.run(arguments, text=True, capture_output=True, env=environment, check=False)
    output = done.stdout + done.stderr
    result = parse_worker_result(done.stdout) or {"status": "failed", "error": "worker emitted no MULTIOP_NPU_RESULT"}
    return result, output, (time.monotonic() - started) * 1000.0, done.returncode


def compact_failure(output: str) -> str:
    records = [line for line in output.splitlines() if line.startswith("MULTIOP_NPU_RESULT ")]
    return (records[-1] if records else output[-2500:])[:2500]


class RotatingJsonl:
    """Append JSON lines to numbered logs without ever exceeding 50 MiB."""

    def __init__(self, directory: Path, maximum_bytes: int = MAX_LOG_BYTES) -> None:
        self.directory = directory
        self.maximum_bytes = maximum_bytes
        self.directory.mkdir(parents=True, exist_ok=True)
        numbers = [int(path.stem) for path in self.directory.glob("*.log") if path.stem.isdigit()]
        self.index = max(numbers, default=1)

    def append(self, row: dict[str, Any]) -> Path:
        encoded = json.dumps(row, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8") + b"\n"
        if len(encoded) > self.maximum_bytes:
            raise RuntimeError("one campaign record exceeds the 50 MiB log limit")
        path = self.directory / f"{self.index}.log"
        existing = path.stat().st_size if path.is_file() else 0
        if existing and existing + len(encoded) > self.maximum_bytes:
            self.index += 1
            path = self.directory / f"{self.index}.log"
        with path.open("ab") as handle:
            handle.write(encoded)
            handle.flush()
        return path


def emit(writer: RotatingJsonl, row: dict[str, Any]) -> None:
    """Write every formal point and every candidate rejection as log records.

    The workload summary is deliberately separate from its formal candidates:
    this makes a missing candidate observable rather than silently hidden in
    a nested progress blob, while resume still keys solely on the summary.
    """
    common = {"schema": row["schema"], "group_key": row["group_key"], "workload": row["workload"]}
    for rank, candidate in enumerate(row.get("valid_latency", []), start=1):
        writer.append({**common, "record_type": "formal_latency_candidate", "rank": rank,
                       "candidate": candidate})
    for phase in ("discovery", "verification", "measurement"):
        for detail in row.get(f"{phase}_failures", []):
            writer.append({**common, "record_type": "candidate_rejected", "phase": phase,
                           "reason": detail})
    summary = dict(row)
    summary.pop("valid_latency", None)
    summary["record_type"] = "workload"
    writer.append(summary)
    # Keep the terminal useful during a 20k-record background campaign.  Full
    # identities, output checks, latency samples, and rejection causes stay
    # in the rotating logs rather than being duplicated to the terminal.
    workload = row.get("workload", {})
    discovery = row.get("source_discovery", {})
    summary = {
        "schema": row.get("schema"), "status": row.get("status"),
        "op": workload.get("op"), "workload_id": workload.get("workload_id"),
        "valid_latency_count": row.get("valid_latency_count", 0),
        "distinct_raw_tilings": discovery.get("distinct_raw_tilings"),
        "attempted_source_contexts": discovery.get("attempted_source_contexts"),
        "rejection_reason": row.get("rejection_reason"),
    }
    print("SOURCE_TILING_GROUP_RESULT " + json.dumps(summary, ensure_ascii=False, sort_keys=True), flush=True)


def iter_log_rows(directory: Path) -> Any:
    if not directory.is_dir():
        return
    paths = sorted((path for path in directory.glob("*.log") if path.stem.isdigit()), key=lambda path: int(path.stem))
    for path in paths:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    # A host interruption can leave only the final line
                    # incomplete.  Earlier append-only records remain valid.
                    continue


def read_progress(directory: Path) -> tuple[set[str], dict[str, int], int]:
    completed: set[str] = set()
    admitted: dict[str, int] = {}
    rejected = 0
    for row in iter_log_rows(directory):
        workload = row.get("workload", {})
        if (row.get("schema") != SCHEMA or row.get("record_type") != "workload" or
                row.get("status") not in ("admitted", "rejected", "budget_skipped") or
                not isinstance(row.get("group_key"), str) or not isinstance(workload, dict) or
                workload.get("op") not in RUNTIME_OPERATOR_NAMES):
            continue
        completed.add(row["group_key"])
        if row["status"] == "admitted":
            op = str(workload["op"])
            admitted[op] = admitted.get(op, 0) + int(row.get("valid_latency_count", 0))
        elif row["status"] == "rejected":
            rejected += 1
    return completed, admitted, rejected


def validate_custom_manifest(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise RuntimeError("missing custom OPP manifest: {}".format(path))
    item: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    required = ("schema", "operator", "cmake_op_name", "source_family", "official_commit", "vendor",
                "custom_opp_root", "source_package_sha256", "source_tiling_observation_enabled",
                "source_compile_info_core_budget_enumeration", "source_hardware_envelope_heuristic_enumeration",
                "hardware_envelope_heuristic", "instrumentation", "overlay_manifest_sha256")
    if any(key not in item for key in required) or item["schema"] != "source_candidate_custom_opp_v1":
        raise RuntimeError("invalid generic custom OPP manifest: {}".format(path))
    delivery = item.get("device_kernel_delivery")
    if (not isinstance(delivery, dict) or delivery.get("mode") != "installed_dynamic_source_passthrough" or
            delivery.get("precompiled_all_tiling_keys") is not False or not delivery.get("formal_data_gate")):
        raise RuntimeError("custom package must use installed dynamic device source without bulk key precompilation")
    source_package = Path(str(item.get("source_package", "")))
    if not source_package.is_file() or digest_file(source_package) != str(item["source_package_sha256"]):
        raise RuntimeError("custom package dynamic-device asset attestation is missing or mismatched")
    runtime_op = OPERATOR_RUNTIME_NAMES.get(str(item["operator"]))
    if runtime_op is None:
        raise RuntimeError("custom package is not an allowed non-MatMul operator: {}".format(item["operator"]))
    source_name = str(item["source_family"])
    if source_name not in LOCK["sources"] or item["official_commit"] != LOCK["sources"][source_name].get("commit"):
        raise RuntimeError("custom package official source provenance is mismatched")
    inst = item["instrumentation"]
    if (not isinstance(inst, dict) or inst.get("enabled") is not True or inst.get("mutates_tiling_context") is not False or
            not inst.get("audit_schema") or not inst.get("audit_environment") or not inst.get("source_budget_environment") or
            item["source_tiling_observation_enabled"] is not True or item["source_compile_info_core_budget_enumeration"] is not True):
        raise RuntimeError("custom package does not attest an observational original-source candidate axis")
    envelope = item["hardware_envelope_heuristic"]
    if (not isinstance(envelope, dict) or envelope.get("enabled") != bool(item["source_hardware_envelope_heuristic_enumeration"]) or
            (envelope.get("enabled") and (not envelope.get("environment") or not envelope.get("audit_field") or
                                           tuple(envelope.get("divisors", ())) != (2, 4, 8) or int(envelope.get("max_anchors", 0)) < 1))):
        raise RuntimeError("custom package hardware-envelope provenance is invalid")
    custom_root = Path(str(item["custom_opp_root"]))
    if not (custom_root / "vendors" / str(item["vendor"])).is_dir():
        raise RuntimeError("isolated custom OPP vendor root is missing: {}".format(custom_root))
    item["runtime_op"] = runtime_op
    compatibility = item.get("compatibility_port")
    if compatibility is not None and (not isinstance(compatibility, dict) or
                                      compatibility.get("tiling_algorithm_changes") is not False or
                                      compatibility.get("kernel_algorithm_changes") is not False or
                                      not compatibility.get("formal_data_gate")):
        raise RuntimeError("custom package compatibility port exceeds source-preserving limits")
    item["manifest_path"] = str(path)
    return item


def read_observations(path: Path, schema: str) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    rows: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if value.get("schema") == schema:
            rows.append(value)
    return rows


def raw_identity(observation: dict[str, Any]) -> str:
    fields = ("tiling_key", "block_dim", "raw_bytes", "raw_fnv1a64")
    if any(field not in observation for field in fields):
        raise RuntimeError("source audit omitted its raw tiling identity")
    return ":".join(str(observation[field]) for field in fields)


def successful_observation(path: Path, package: dict[str, Any]) -> tuple[dict[str, Any] | None, str | None]:
    rows = read_observations(path, str(package["instrumentation"]["audit_schema"]))
    if not rows:
        return None, "original-source overlay emitted no audit observation"
    identities = {raw_identity(row) for row in rows}
    if len(identities) != 1:
        return None, "one source context emitted multiple raw identities"
    if any(int(row.get("status", -1)) != 0 for row in rows):
        return None, "original source tiler returned a non-success status"
    result = dict(rows[-1])
    result["raw_tiling_identity"] = next(iter(identities))
    result["observation_count"] = len(rows)
    return result, None


def candidate_descriptor(package: dict[str, Any], cap: int, l2_divisor: int = 1) -> dict[str, Any]:
    if l2_divisor not in (1, 2, 4, 8):
        raise RuntimeError("invalid source L2-envelope divisor")
    heuristic = l2_divisor != 1
    envelope = package["hardware_envelope_heuristic"]
    return {
        "kind": "hardware_rule_heuristic_from_original_source_context" if heuristic else "original_source_tiler_with_runtime_bounded_core_budget",
        "origin": "hardware_rule_heuristic" if heuristic else "original_source",
        "id": package.get("strategy_class") or "original_semantic_dispatch",
        "priority": package.get("strategy_priority"), "aiv_core_cap": int(cap),
        "hardware_envelope_resource": envelope.get("resource"), "hardware_envelope_divisor": int(l2_divisor),
        "source_package_sha256": package["source_package_sha256"], "official_commit": package["official_commit"],
    }


def candidate_label(candidate: dict[str, Any]) -> str:
    resource = candidate.get("hardware_envelope_resource") or "none"
    return "{}@aiv{}@{}/{}".format(candidate["id"], candidate["aiv_core_cap"], resource, candidate["hardware_envelope_divisor"])


def context_matches(observation: dict[str, Any] | None, candidate: dict[str, Any], package: dict[str, Any]) -> bool:
    if observation is None or str(observation.get("aiv_core_cap")) != str(candidate["aiv_core_cap"]):
        return False
    envelope = package["hardware_envelope_heuristic"]
    if envelope["enabled"]:
        return str(observation.get(str(envelope["audit_field"]), "1")) == str(candidate["hardware_envelope_divisor"])
    return candidate["hardware_envelope_divisor"] == 1


def source_environment(base: dict[str, str], package: dict[str, Any], candidate: dict[str, Any], audit: Path) -> dict[str, str]:
    environment = dict(base)
    environment["ASCEND_CUSTOM_OPP_PATH"] = str(package["custom_opp_root"])
    environment[str(package["instrumentation"]["audit_environment"])] = str(audit)
    environment[str(package["instrumentation"]["source_budget_environment"])] = str(candidate["aiv_core_cap"])
    envelope = package["hardware_envelope_heuristic"]
    if envelope["enabled"]:
        environment[str(envelope["environment"])] = str(candidate["hardware_envelope_divisor"])
    return environment


def plan_packages(manifests: list[dict[str, Any]], catalog: Any) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for package in manifests:
        grouped.setdefault(str(package["runtime_op"]), []).append(package)
    if set(grouped) != set(RUNTIME_OPERATOR_NAMES):
        missing = sorted(set(RUNTIME_OPERATOR_NAMES) - set(grouped))
        raise RuntimeError("all four source collectors must be present before the campaign starts; missing={}".format(missing))
    required_fasg = set(catalog.FASG_SOURCE_STRATEGY_CLASSES)
    fasg = grouped["flash_attention_score_grad"]
    classes = {str(item.get("strategy_class")) for item in fasg}
    if len(fasg) != len(classes) or classes != required_fasg:
        raise RuntimeError("FASG must retain all eight original registered strategies")
    if any(item["source_hardware_envelope_heuristic_enumeration"] is not True for item in fasg):
        raise RuntimeError("FASG package provenance lacks its explicit conditional L2 heuristic")
    for op in ("fused_infer_attention_score", "gather_elements"):
        if len(grouped[op]) != 1 or grouped[op][0]["hardware_envelope_heuristic"]["enabled"] is not True:
            raise RuntimeError("{} requires one original semantic dispatcher plus its declared conditional capacity envelope".format(op))
    if len(grouped["scatter_elements"]) != 1 or grouped["scatter_elements"][0]["hardware_envelope_heuristic"]["enabled"] is not True:
        raise RuntimeError("ScatterElements requires its documented single source dispatcher plus conditional UB-envelope heuristic")
    return grouped


def select_heuristic_anchors(discovered: dict[str, dict[str, Any]], maximum: int) -> list[dict[str, Any]]:
    by_id: dict[str, list[dict[str, Any]]] = {}
    seen: set[str] = set()
    for item in discovered.values():
        for origin in item["source_origins"]:
            if origin["hardware_envelope_divisor"] != 1:
                continue
            key = stable_hash(origin)
            if key not in seen:
                seen.add(key)
                by_id.setdefault(str(origin["id"]), []).append(origin)
    for values in by_id.values():
        values.sort(key=lambda row: (int(row["aiv_core_cap"]), str(row["id"])))
    selected: list[dict[str, Any]] = []
    while len(selected) < maximum and any(by_id.values()):
        for name in sorted(by_id):
            if by_id[name] and len(selected) < maximum:
                selected.append(by_id[name].pop(0))
    return selected


def discover_group(args: Any, workload: dict[str, Any], packages: list[dict[str, Any]], caps: tuple[int, ...], minimum: int,
                   base_env: dict[str, str], group_key: str, temp: Path, catalog: Any) -> tuple[dict[str, dict[str, Any]], dict[str, Any], list[str]]:
    discovered: dict[str, dict[str, Any]] = {}
    failures: list[str] = []
    successful_contexts = original_contexts = heuristic_contexts = 0
    def attempt(package: dict[str, Any], candidate: dict[str, Any], kind: str) -> None:
        nonlocal successful_contexts, original_contexts, heuristic_contexts
        if kind == "original": original_contexts += 1
        else: heuristic_contexts += 1
        audit = temp / ("discover_" + stable_hash({"g": group_key, "c": candidate}) + ".jsonl")
        result, output, wall, rc = run_worker(worker_args(args.runner, workload, args.device, 0, 0) + ["--source-tiling-only"],
                                              source_environment(base_env, package, candidate, audit))
        observed, reason = successful_observation(audit, package)
        if rc != 0 or result.get("status") != "success" or not context_matches(observed, candidate, package):
            failures.append(candidate_label(candidate) + ": " + (reason or compact_failure(output)))
            return
        successful_contexts += 1
        identity = str(observed["raw_tiling_identity"])
        entry = discovered.setdefault(identity, {"candidate": candidate, "package": package, "source_origins": [],
                                                 "source_tiling_observation": observed, "discovery_wall_ms": wall})
        entry["source_origins"].append(candidate)
    for package in packages:
        for cap in caps:
            attempt(package, candidate_descriptor(package, cap), "original")
    anchors: list[dict[str, Any]] = []
    envelope = packages[0]["hardware_envelope_heuristic"]
    if len(discovered) < minimum and envelope["enabled"] and all(package["hardware_envelope_heuristic"] == envelope for package in packages):
        anchors = select_heuristic_anchors(discovered, int(envelope["max_anchors"]))
        by_id = {str(package.get("strategy_class")): package for package in packages}
        for anchor in anchors:
            for divisor in envelope["divisors"]:
                package = by_id[str(anchor["id"])]
                attempt(package, candidate_descriptor(package, int(anchor["aiv_core_cap"]), int(divisor)), "heuristic")
    report = {"attempted_source_contexts": original_contexts + heuristic_contexts,
              "attempted_original_source_contexts": original_contexts, "attempted_hardware_rule_heuristic_contexts": heuristic_contexts,
              "successful_source_contexts": successful_contexts, "distinct_raw_tilings": len(discovered),
              "heuristic_anchor_count": len(anchors)}
    return discovered, report, failures


def execute_group(args: Any, workload: dict[str, Any], packages: list[dict[str, Any]], caps: tuple[int, ...], minimum: int,
                  ceiling: int, base_env: dict[str, str], group_key: str, temp: Path, catalog: Any) -> tuple[str, dict[str, Any]]:
    reference_path = temp / "reference.bin"
    reference, output, wall, rc = run_worker(worker_args(args.runner, workload, args.device, 0, 0) + ["--write-reference", str(reference_path)], base_env)
    if rc != 0 or reference.get("status") != "success" or not reference_path.is_file():
        return "rejected", {"rejection_reason": "installed reference execution failed", "failure": compact_failure(output), "worker_wall_ms": wall}
    discovered, discovery, failures = discover_group(args, workload, packages, caps, minimum, base_env, group_key, temp, catalog)
    if len(discovered) < minimum:
        return "rejected", {"rejection_reason": "fewer than 20 distinct raw tilings from the complete source search", "source_discovery": discovery, "discovery_failures": failures}
    verified: list[dict[str, Any]] = []
    verification_failures: list[str] = []
    for identity, item in discovered.items():
        candidate, package = item["candidate"], item["package"]
        audit = temp / ("verify_" + stable_hash({"g": group_key, "c": candidate}) + ".jsonl")
        result, output, wall, rc = run_worker(worker_args(args.runner, workload, args.device, 0, 0) + ["--compare-reference", str(reference_path)],
                                              source_environment(base_env, package, candidate, audit))
        observed, reason = successful_observation(audit, package)
        equal = bool(result.get("output_reference_checked")) and bool(result.get("output_reference_equal"))
        if rc != 0 or result.get("status") != "success" or not equal or not context_matches(observed, candidate, package) or observed.get("raw_tiling_identity") != identity:
            verification_failures.append(candidate_label(candidate) + ": " + (reason or "output/reference or raw identity mismatch"))
            continue
        verified.append({**item, "verification_result": result, "verification_wall_ms": wall, "verification_tiling_observation": observed})
    if len(verified) < minimum:
        return "rejected", {"rejection_reason": "fewer than 20 distinct source tilings passed exact output validation", "source_discovery": discovery,
                              "successful_verified_distinct_tilings": len(verified), "discovery_failures": failures,
                              "verification_failures": verification_failures}
    if len(verified) > ceiling:
        return "budget_skipped", {"reason": "atomic group would exceed its operator/global record ceiling", "source_discovery": discovery,
                                   "successful_verified_distinct_tilings": len(verified), "remaining_record_budget": ceiling}
    measured: list[dict[str, Any]] = []
    measurement_failures: list[str] = []
    for item in verified:
        candidate, package = item["candidate"], item["package"]
        audit = temp / ("measure_" + stable_hash({"g": group_key, "c": candidate}) + ".jsonl")
        result, output, wall, rc = run_worker(worker_args(args.runner, workload, args.device, args.warmup, args.samples) + ["--compare-reference", str(reference_path)],
                                              source_environment(base_env, package, candidate, audit))
        observed, reason = successful_observation(audit, package)
        equal = bool(result.get("output_reference_checked")) and bool(result.get("output_reference_equal"))
        if (rc != 0 or result.get("status") != "success" or not equal or not context_matches(observed, candidate, package) or
                observed.get("raw_tiling_identity") != item["source_tiling_observation"]["raw_tiling_identity"]):
            measurement_failures.append(candidate_label(candidate) + ": " + (reason or "measurement output/reference or raw identity mismatch"))
            continue
        compact = {key: value for key, value in item.items() if key != "package"}
        compact.update({"latency_result": result, "latency_tiling_observation": observed, "latency_worker_wall_ms": wall})
        measured.append(compact)
    # A source candidate that later fails execution is rejected individually;
    # it does not erase other legal candidates.  The shape is useful only
    # when it still has the requested twenty successful, measured tilings.
    if len(measured) < minimum:
        return "rejected", {"rejection_reason": "fewer than 20 source tilings completed real measurement", "source_discovery": discovery,
                              "successful_verified_distinct_tilings": len(verified), "successful_measured_distinct_tilings": len(measured),
                              "discovery_failures": failures, "verification_failures": verification_failures,
                              "measurement_failures": measurement_failures}
    return "admitted", {"valid_latency_count": len(measured), "valid_latency": measured, "source_discovery": discovery,
                         "discovery_failures": failures, "verification_failures": verification_failures,
                         "measurement_failures": measurement_failures,
                         "rejected_candidate_count": len(failures) + len(verification_failures) + len(measurement_failures),
                         "source_rule": "complete original-source candidate set, then only the package-declared source-visible capacity envelope when that set has fewer than 20 identities; failed candidates do not count; no raw-field generation"}


def summarize(directory: Path) -> dict[str, Any]:
    _, per_op, rejected = read_progress(directory)
    return {"formal_valid_latency_records": sum(per_op.values()), "formal_valid_latency_records_per_op": per_op, "rejected_groups": rejected}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runner", required=True, type=Path)
    parser.add_argument("--log-dir", required=True, type=Path,
                        help="append-only numbered JSONL logs; each file is capped at 50 MiB")
    parser.add_argument("--device", required=True, type=int)
    parser.add_argument("--warmup", type=int, default=2)
    parser.add_argument("--samples", type=int, default=5)
    parser.add_argument("--custom-opp-manifest", action="append", default=[], type=Path)
    args = parser.parse_args()
    if not args.runner.is_file() or args.device < 0 or args.warmup < 0 or args.samples < 1:
        raise RuntimeError("invalid worker runner or measurement arguments")
    workloads, audit, catalog = load_catalog()
    minimum = int(catalog.MIN_SUCCESSFUL_TILINGS_PER_SHAPE)
    caps = tuple(int(value) for value in catalog.SOURCE_AIV_CAPS)
    budgets = {str(key): int(value) for key, value in catalog.FORMAL_RECORD_BUDGET_PER_OP.items()}
    if minimum != 20 or not caps or sum(budgets.values()) != int(audit["formal_latency_target"]):
        raise RuntimeError("campaign requires 20 candidates per group and an exact global 20,000-record ceiling")
    packages = plan_packages([validate_custom_manifest(path) for path in args.custom_opp_manifest], catalog)
    writer = RotatingJsonl(args.log_dir)
    completed, admitted_by_op, prior_rejected = read_progress(args.log_dir)
    if any(admitted_by_op.get(op, 0) > budgets[op] for op in budgets):
        raise RuntimeError("existing progress exceeds a per-operator formal record ceiling")
    base_env = dict(os.environ)
    base_env.pop("ASCEND_CUSTOM_OPP_PATH", None)
    for package_set in packages.values():
        for package in package_set:
            base_env.pop(str(package["instrumentation"]["audit_environment"]), None)
            base_env.pop(str(package["instrumentation"]["source_budget_environment"]), None)
    for package_set in packages.values():
        for package in package_set:
            envelope = package["hardware_envelope_heuristic"]
            if envelope["enabled"]:
                base_env.pop(str(envelope["environment"]), None)
    runner_hash = digest_file(args.runner)
    planned = {op: [row for row in workloads if row["op"] == op] for op in budgets}
    begin = {
        "schema": SCHEMA, "matmul_included": False, "formal_latency_ceiling": int(audit["formal_latency_target"]),
        "formal_record_budget_per_op": budgets, "per_shape_minimum_successful_distinct_tilings": minimum,
        "candidate_collection": "complete original-source set; declared local hardware-rule capacity envelope only after original set is below 20",
        "operators": {op: {"semantic_workloads": len(planned[op]), "source_package_count": len(packages[op])} for op in budgets},
        "historical_latency_or_tiling_records_read": 0, "cce_data_or_cost_model_read": 0,
        "timing": {"warmup": args.warmup, "samples": args.samples, "kind": "device_event_only"},
        "no_host_timeout_or_forced_worker_kill": True, "temporary_reference_storage": "/tmp only",
        "log_directory": str(args.log_dir), "log_rotation_max_bytes": MAX_LOG_BYTES,
    }
    writer.append({**begin, "record_type": "campaign_begin"})
    print("SOURCE_TILING_CAMPAIGN_BEGIN " + json.dumps(begin, ensure_ascii=False, sort_keys=True), flush=True)
    max_len = max(len(rows) for rows in planned.values())
    for index in range(max_len):
        for op in budgets:
            if index >= len(planned[op]) or admitted_by_op.get(op, 0) >= budgets[op]:
                continue
            workload = planned[op][index]
            group_key = stable_hash({"workload": workload, "runner_sha256": runner_hash,
                                     "package_manifests": [p["overlay_manifest_sha256"] for p in packages[op]],
                                     "source_aiv_caps": caps, "minimum": minimum, "schema": SCHEMA})
            if group_key in completed:
                continue
            remaining = min(budgets[op] - admitted_by_op.get(op, 0), int(audit["formal_latency_target"]) - sum(admitted_by_op.values()))
            if remaining < minimum:
                continue
            with tempfile.TemporaryDirectory(prefix=op + "_source_tiling_") as temporary:
                status, details = execute_group(args, workload, packages[op], caps, minimum, remaining,
                                                base_env, group_key, Path(temporary), catalog)
            row = {"schema": SCHEMA, "group_key": group_key, "status": status, "workload": workload, **details}
            if status != "admitted":
                row.setdefault("valid_latency_count", 0)
            emit(writer, row)
            completed.add(group_key)
            if status == "admitted":
                admitted_by_op[op] = admitted_by_op.get(op, 0) + int(details["valid_latency_count"])
    end = {"schema": SCHEMA, "matmul_included": False,
          "status": "complete" if sum(admitted_by_op.values()) == int(audit["formal_latency_target"]) else "completed_under_atomic_ceiling",
          "summary": summarize(args.log_dir), "prior_rejected_groups": prior_rejected,
          "log_directory": str(args.log_dir), "log_rotation_max_bytes": MAX_LOG_BYTES}
    writer.append({**end, "record_type": "campaign_end"})
    print("SOURCE_TILING_CAMPAIGN_END " + json.dumps(end, ensure_ascii=False, sort_keys=True), flush=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as error:
        print("SOURCE_TILING_CAMPAIGN_FATAL " + json.dumps({"error": str(error)}, ensure_ascii=False), file=sys.stderr)
        raise SystemExit(2)
